//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomRPC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomRPC.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you allow CustomRP to send your usage analytics to the developer?
        ///(All the data is depersonalized.).
        /// </summary>
        internal static string askAnalyticsConsent {
            get {
                return ResourceManager.GetString("askAnalyticsConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete application&apos;s settings?
        ///This cannot be undone..
        /// </summary>
        internal static string deleteSettings {
            get {
                return ResourceManager.GetString("deleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to Discord client.
        ///Are you sure it&apos;s running?.
        /// </summary>
        internal static string errorCannotConnect {
            get {
                return ResourceManager.GetString("errorCannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file is corrupted.
        ///Press Yes to reset the settings, press No to quit..
        /// </summary>
        internal static string errorCorruptSettings {
            get {
                return ResourceManager.GetString("errorCorruptSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image URL is too long!.
        /// </summary>
        internal static string errorInvalidImageURL {
            get {
                return ResourceManager.GetString("errorInvalidImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import preset; the file is either missing, corrupted, or not properly formatted..
        /// </summary>
        internal static string errorInvalidPresetFile {
            get {
                return ResourceManager.GetString("errorInvalidPresetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL specified for button(s) or the text is too long!.
        /// </summary>
        internal static string errorInvalidURL {
            get {
                return ResourceManager.GetString("errorInvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add &quot;{0}&quot; path to your antivirus&apos;s exceptions. Reinstall CustomRP if this error persists..
        /// </summary>
        internal static string errorLoadingAssembly {
            get {
                return ResourceManager.GetString("errorLoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ID specified!.
        /// </summary>
        internal static string errorNoID {
            get {
                return ResourceManager.GetString("errorNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the internet!.
        /// </summary>
        internal static string errorNoInternet {
            get {
                return ResourceManager.GetString("errorNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the URL. It has been copied to the clipboard..
        /// </summary>
        internal static string errorOpeningURL {
            get {
                return ResourceManager.GetString("errorOpeningURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the settings:.
        /// </summary>
        internal static string errorSavingSettings {
            get {
                return ResourceManager.GetString("errorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add or remove a startup shortcut:.
        /// </summary>
        internal static string errorStartupShortcut {
            get {
                return ResourceManager.GetString("errorStartupShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error downloading or installing an update.
        ///Press &quot;Yes&quot; to retry or &quot;No&quot; to download manually..
        /// </summary>
        internal static string errorUpdateFailed {
            get {
                return ResourceManager.GetString("errorUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        internal static string firstTimeRun {
            get {
                return ResourceManager.GetString("firstTimeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the manual?
        ///You can open it any time by going to Help -&gt; Open the Manual or pressing F1..
        /// </summary>
        internal static string firstTimeRunText {
            get {
                return ResourceManager.GetString("firstTimeRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start from scratch?
        ///This cannot be undone..
        /// </summary>
        internal static string newPresetConfirmation {
            get {
                return ResourceManager.GetString("newPresetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found!.
        /// </summary>
        internal static string noUpdatesFound {
            get {
                return ResourceManager.GetString("noUpdatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competing.
        /// </summary>
        internal static string presenceTypeCompeting {
            get {
                return ResourceManager.GetString("presenceTypeCompeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        internal static string presenceTypeListening {
            get {
                return ResourceManager.GetString("presenceTypeListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string presenceTypePlaying {
            get {
                return ResourceManager.GetString("presenceTypePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        internal static string presenceTypeWatching {
            get {
                return ResourceManager.GetString("presenceTypeWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Preset Directory.
        /// </summary>
        internal static string setPresetDirectory {
            get {
                return ResourceManager.GetString("setPresetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string statusConnected {
            get {
                return ResourceManager.GetString("statusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string statusConnecting {
            get {
                return ResourceManager.GetString("statusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed (Is Discord running?).
        /// </summary>
        internal static string statusConnectionFailed {
            get {
                return ResourceManager.GetString("statusConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string statusDisconnected {
            get {
                return ResourceManager.GetString("statusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error (Wrong ID?).
        /// </summary>
        internal static string statusError {
            get {
                return ResourceManager.GetString("statusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating presence....
        /// </summary>
        internal static string statusUpdatingPresence {
            get {
                return ResourceManager.GetString("statusUpdatingPresence", resourceCulture);
            }
        }
    }
}
